### ISSUE TITLE
[FR] Stream line more with HA architecture;  last_reported and availability

### ISSUE THREAD

**Issue by erkr** [aequitas/python-rflink#76]
Hi

Thirst thanks for maintaining the RFLINK integration in HA. I'm using it for several years and it works great.
In the mean time HA architecture for integration entities evolved, and I believe RFLINK could be more streamlined. 

My FR is to add _availability_ awareness and _last reported_ to RFLINK sensors.

Sensor example: 
```
      oregonv1_004c_temp:
        sensor_type: temperature
        name: rf433 Tuinhuis Temperature

      oregonv1_004c_update_time:
        sensor_type: timestamp
        name: rf433 Tuinhuis update_time
        unit_of_measurement: 's'
```

This _update_time_ sensor is created by RFLINK, but it would be more consistent to remove this extra sensor and use it for _availability_ and _last reported_ instead.
For availability a configurable timeout would be enough with (default 0 for no timeout to stay backwards compatibile)

Configuration would then become:
```
      oregonv1_004c_temp:
        sensor_type: temperature
        name: rf433 Tuinhuis Temperature
        availability: 600 #seconds
```

In the general RFLINK config an option could be added to disable these extra  update_time sensors (default false to stay backwards compatibile)

My 2 cents
Eric
